/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Quectel-Admin",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "布局",
      "frontmatter": {},
      "regularPath": "/guide/layout.html",
      "relativePath": "guide/layout.md",
      "key": "v-b2c0ef52",
      "path": "/guide/layout.html",
      "headers": [
        {
          "level": 3,
          "title": "配置页面",
          "slug": "配置页面"
        },
        {
          "level": 3,
          "title": "配置自定义页面",
          "slug": "配置自定义页面"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/quectel.jpg",
        "heroText": "Quectel-admin",
        "tagline": "PC端前端框架封装",
        "actionText": "使用文档 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "技术栈",
            "details": "使用 vue/vuex/vue-router/element 等前端技术开发"
          },
          {
            "title": "丰富功能",
            "details": "提炼了典型的业务模型，提供了丰富的功能组件"
          },
          {
            "title": "国际化",
            "details": "默认中英文切换"
          }
        ],
        "footer": "© 上海移远通信技术股份有限公司 - 版权所有"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-817b6fee",
      "path": "/"
    },
    {
      "title": "目录结构",
      "frontmatter": {},
      "regularPath": "/guide/Directory.html",
      "relativePath": "guide/Directory.md",
      "key": "v-7603ee36",
      "path": "/guide/Directory.html"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/index.md",
      "key": "v-6fcf8484",
      "path": "/guide/"
    },
    {
      "title": "路由和导航",
      "frontmatter": {},
      "regularPath": "/guide/router.html",
      "relativePath": "guide/router.md",
      "key": "v-fd1db64e",
      "path": "/guide/router.html",
      "headers": [
        {
          "level": 3,
          "title": "路由和导航",
          "slug": "路由和导航"
        },
        {
          "level": 3,
          "title": "配置项",
          "slug": "配置项"
        },
        {
          "level": 3,
          "title": "路由",
          "slug": "路由"
        }
      ]
    },
    {
      "title": "框架安装",
      "frontmatter": {},
      "regularPath": "/guide/install.html",
      "relativePath": "guide/install.md",
      "key": "v-15f0b525",
      "path": "/guide/install.html",
      "headers": [
        {
          "level": 3,
          "title": "框架安装",
          "slug": "框架安装"
        },
        {
          "level": 3,
          "title": "UI组件安装",
          "slug": "ui组件安装"
        }
      ]
    },
    {
      "title": "Mock Data",
      "frontmatter": {},
      "regularPath": "/guide/mock.html",
      "relativePath": "guide/mock.md",
      "key": "v-4c71d552",
      "path": "/guide/mock.html",
      "headers": [
        {
          "level": 3,
          "title": "Mock Data",
          "slug": "mock-data"
        },
        {
          "level": 3,
          "title": "Mockjs",
          "slug": "mockjs"
        },
        {
          "level": 3,
          "title": "移除",
          "slug": "移除"
        },
        {
          "level": 3,
          "title": "新增",
          "slug": "新增"
        },
        {
          "level": 3,
          "title": "修改",
          "slug": "修改"
        },
        {
          "level": 3,
          "title": "多个 server",
          "slug": "多个-server"
        },
        {
          "level": 3,
          "title": "启用纯前端 Mock",
          "slug": "启用纯前端-mock"
        },
        {
          "level": 3,
          "title": "本地 Mock 数据与线上数据切换",
          "slug": "本地-mock-数据与线上数据切换"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "使用手册",
        "link": "/guide/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/xiaoWangHi/quectel-admin.git"
      }
    ],
    "sidebar": [
      {
        "title": "介绍",
        "path": "/guide/"
      },
      {
        "title": "安装",
        "path": "/guide/install"
      },
      {
        "title": "基础",
        "collapsable": false,
        "children": [
          {
            "title": "目录结构",
            "path": "/guide/Directory"
          },
          {
            "title": "页面布局",
            "path": "/guide/layout"
          },
          {
            "title": "路由和导航",
            "path": "/guide/router"
          },
          {
            "title": "Mock",
            "path": "/guide/mock"
          },
          {
            "title": "与后端接口调试",
            "path": "/guide/install"
          },
          {
            "title": "国际化",
            "path": "/guide/install"
          }
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          {
            "title": "面包屑",
            "path": "/guide/install"
          },
          {
            "title": "快速导航",
            "path": "/guide/install"
          },
          {
            "title": "表格",
            "path": "/guide/install"
          },
          {
            "title": "上传",
            "path": "/guide/install"
          },
          {
            "title": "图表",
            "path": "/guide/install"
          },
          {
            "title": "表单",
            "path": "/guide/install"
          },
          {
            "title": "按钮",
            "path": "/guide/install"
          },
          {
            "title": "图标",
            "path": "/guide/install"
          },
          {
            "title": "标签页",
            "path": "/guide/install"
          },
          {
            "title": "对话框",
            "path": "/guide/install"
          },
          {
            "title": "抽屉",
            "path": "/guide/install"
          },
          {
            "title": "进度条",
            "path": "/guide/install"
          },
          {
            "title": "图片剪裁",
            "path": "/guide/install"
          },
          {
            "title": "日历",
            "path": "/guide/install"
          },
          {
            "title": "时间轴",
            "path": "/guide/install"
          },
          {
            "title": "步骤条",
            "path": "/guide/install"
          },
          {
            "title": "树形控件",
            "path": "/guide/install"
          }
        ]
      }
    ]
  }
}