/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Quectel-Admin",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/guide/install.html",
      "relativePath": "guide/install.md",
      "key": "v-15f0b525",
      "path": "/guide/install.html",
      "headers": [
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/index.md",
      "key": "v-6fcf8484",
      "path": "/guide/"
    },
    {
      "title": "目录结构",
      "frontmatter": {},
      "regularPath": "/guide/Directory.html",
      "relativePath": "guide/Directory.md",
      "key": "v-7603ee36",
      "path": "/guide/Directory.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/quectel.jpg",
        "heroText": "Quectel-admin",
        "tagline": "PC端前端框架封装",
        "actionText": "使用文档 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "技术栈",
            "details": "使用 vue/vuex/vue-router/element 等前端技术开发"
          },
          {
            "title": "丰富功能",
            "details": "提炼了典型的业务模型，提供了丰富的功能组件"
          },
          {
            "title": "国际化",
            "details": "默认中英文切换"
          }
        ],
        "footer": "© 上海移远通信技术股份有限公司 - 版权所有"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-817b6fee",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "使用手册",
        "link": "/guide/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/xiaoWangHi/quectel-admin.git"
      }
    ],
    "sidebar": [
      {
        "title": "介绍",
        "path": "/guide/"
      },
      {
        "title": "安装",
        "path": "/guide/install"
      },
      {
        "title": "基础",
        "collapsable": false,
        "children": [
          {
            "title": "目录结构",
            "path": "/guide/Directory"
          },
          {
            "title": "页面布局",
            "path": "/guide/install"
          },
          {
            "title": "路由",
            "path": "/guide/install"
          },
          {
            "title": "Mock",
            "path": "/guide/install"
          },
          {
            "title": "与后端接口调试",
            "path": "/guide/install"
          },
          {
            "title": "国际化",
            "path": "/guide/install"
          }
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          {
            "title": "面包屑",
            "path": "/guide/install"
          },
          {
            "title": "快速导航",
            "path": "/guide/install"
          },
          {
            "title": "表格",
            "path": "/guide/install"
          },
          {
            "title": "上传",
            "path": "/guide/install"
          },
          {
            "title": "图表",
            "path": "/guide/install"
          },
          {
            "title": "表单",
            "path": "/guide/install"
          },
          {
            "title": "按钮",
            "path": "/guide/install"
          },
          {
            "title": "图标",
            "path": "/guide/install"
          },
          {
            "title": "标签页",
            "path": "/guide/install"
          },
          {
            "title": "对话框",
            "path": "/guide/install"
          },
          {
            "title": "抽屉",
            "path": "/guide/install"
          },
          {
            "title": "进度条",
            "path": "/guide/install"
          },
          {
            "title": "图片剪裁",
            "path": "/guide/install"
          },
          {
            "title": "日历",
            "path": "/guide/install"
          },
          {
            "title": "时间轴",
            "path": "/guide/install"
          },
          {
            "title": "步骤条",
            "path": "/guide/install"
          },
          {
            "title": "树形控件",
            "path": "/guide/install"
          }
        ]
      }
    ]
  }
}